### ISSUE TITLE
Questionnaire_EnableWhenOperatorKind doesn't match FHIR R4 spec

### ISSUE THREAD

**Issue by JWess** [Ahryman40k/typescript-fhir-types#20]
The type `Questionnaire_EnableWhenOperatorKind ` uses words ("Equal", "Greater", ...) instead of symbols ("=", ">"). 

See the spec here:
https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.enableWhen.operator

**Comment by Ahryman40k** [comment]
Hi Joel, 

Thank you for your contribution and your PR.
I try to remember if words instead of logical operators were intended or not. I just check that point first before merging your PR. 
Have you made some tests to ensure a JSON will be successfully checked ? and an object using this enum generates a valid JSON ? It exists a lot of tests in the library but this enum may not be checked in any of them.

**Comment by JWess** [comment]
> Hi Joel,
> 
> Thank you for your contribution and your PR.
> I try to remember if words instead of logical operators were intended or not. I just check that point first before merging your PR.
> Have you made some tests to ensure a JSON will be successfully checked ? and an object using this enum generates a valid JSON ? It exists a lot of tests in the library but this enum may not be checked in any of them.

Thanks for merging. Sorry, I did not update any tests.
